apiVersion: v1
kind: Service
metadata:
  name: ollama-service # Must match the name workers use
  namespace: aiswarm
spec:
  selector:
    app: ollama # Selects the pods from the deployment above
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
